import Head from "next/head";
import { AppPropsWithLayout } from "../app/interface/dashboard.interface";
import DashboardLayout from "../app/layout/dashboard-layout";
import "../styles/globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import theme from "../../themes/theme";

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page: React.ReactNode) => page);

  return getLayout(
    <>
      <Head>
        <title>Monitoring Asset KDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChakraProvider theme={theme}>
        {Component.getLayout ? (
          <Component {...pageProps} />
        ) : (
          <DashboardLayout>
            <Component {...pageProps} />
          </DashboardLayout>
        )}
      </ChakraProvider>
    </>
  );
}

export default MyApp;
