import Head from "next/head";
import { AppPropsWithLayout } from "../app/interface/dashboard.interface";
import DashboardLayout from "../app/layout/dashboard-layout";
import "../styles/globals.css";
import { ChakraProvider } from "@chakra-ui/react";

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page: React.ReactNode) => page);

  return getLayout(
    <>
      <Head>
        <title>Monitoring Asset KDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {Component.getLayout ? (
        <ChakraProvider>
          <Component {...pageProps} />
        </ChakraProvider>
      ) : (
        <ChakraProvider>
          <DashboardLayout>
            <Component {...pageProps} />
          </DashboardLayout>
        </ChakraProvider>
      )}
    </>
  );
}

export default MyApp;
